# Site settings
title: Uriel Mendoza
description: ovni
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: https://vumg.github.io/particle/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Uriel Mendoza
user_description: Desarrollador de Software en GDL, MEX. He trabajado en la creacion de prototipos de videjuegos, sprites y sonidos. He mostrado mis conceptos en paginas web interactivas, agregando nuevas experiencias a los usuarios, desde el diseño, maquetación y mantenimiento de cualquier tipo de buena idea.
user_title: Software Developer
email: vumg.ok@gmail.com
twitter_username: https://twitter.com/UrielMendowza
github_username:  https://github.com/vumg
gplus_username:  vumg.ok@gmail.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
